{% set python_min = '3.10' %}
{% set name = "bmi_dbseabed" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2c679f52843d048c58efba5df55b918f8a95e2fe965d5387c097b380f8541a61

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bmi_dbseabed=bmi_dbseabed.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - rioxarray
    - requests
    - pyyaml
    - click
    - bmipy
    - netcdf4
    - owslib

test:
  requires:
    - python {{ python_min }}
  imports:
    - bmi_dbseabed
  commands:
    - bmi_dbseabed --version
    - bmi_dbseabed --help

about:
  home: https://github.com/gantian127/bmi_dbseabed
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    A Python library to fetch the marine substrates data from the dbSEABED system
  description: |
    bmi_dbseabed provides a set of functions that allow downloading of the dataset 
    from dbSEABED, a system for marine substrates datasets across the globe.
    bmi_dbseabed also includes a Basic Model Interface (BMI), which converts the 
    dbSEABED datasets into a reusable, plug-and-play data component (pymt_dbseabed) for 
    the PyMT modeling framework developed by Community Surface Dynamics Modeling System.
  doc_url: https://bmi-dbseabed.readthedocs.io/en/latest/
  dev_url: https://github.com/gantian127/bmi_dbseabed

extra:
  recipe-maintainers:
    - gantian127
